### ISSUE TITLE
Allow filtering of dependency graph view

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#104]
As an architect, I want to filter the services that are shown in the dependency graph view in order to view a subset of the application that is currently relevant to me.

**Comment by georg-schwarz** [comment]
@MBuchalik any ideas to reuse the existing components in that regard?

**Comment by MBuchalik** [comment]
My idea is to integrate as many features as possible into the page. For instance, in #107 we said that we want to have a page for Responsibles. But instead of adding a separate page, we could simply add a button in the grey left side bar that lets the user configure what is shown. By default, we show the Group tree. But if the user wants to, he/she can make the side bar show the services grouped by Responsible, or by Tag, or by whatever.

![grafik](https://user-images.githubusercontent.com/8061217/206421649-3287ed48-8c81-4294-8193-ba499d3f6382.png)

The reason why I am mentioning it here is because this shows that we could reduce the number of separate pages without losing any funcitonality. And we gain a few nice features like the ability to remember the filter the user has set.

**Comment by georg-schwarz** [comment]
Will be solved by #128.
Closing since duplicate.
