### ISSUE TITLE
Refactor client generation

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#87]
The client generation does not support dynamic extension fields (#79). This, and the fact that we need to wrap it anyway on the frontend imply that we can improve here.

I see the following options:
1. Dirty hacks on current solution witch code generation.
2. Copy API models from the server to the client (easy, but no type safety).
3. Shared library for server and client containing the API models (incl. class-validator annotations for model validation).
4. Martin's advanced solution using zod (probably does not play well with nestjs framework).

@MBuchalik do you have an opinion?

**Comment by MBuchalik** [comment]
I do have an idea, but this is most likely an overkill. Let's talk about that in our meeting. Just to give a quick overview:

First of all, as a reminder, this is roughly how my Endpoint Description library (i.e. the super-type-safe library) has defined endpoints:

``` ts
export const SomeEndpointDescription = buildEndpointDescription({
  method: EndpointMethod.POST,

  url: someUrl,
  urlParamsType: z.object({ someParam: z.string() }),

  requestPayloadType: z.object({
     myPayloadParam: z.number(),
  }),

  responseTypes: {
    201: z.object({
      id: z.number(),
    }),
    403: z.undefined(),
    404: z.undefined(),
  },
});
```

We have already seen that it is possible to build custom decorators that invoke other decorators (see e.g. #58). So we could build a decorator that does all of the heavy-lifting for us:

```
@OurApiProperty(SomeEndpointDescription, 201)
async handleTheRequest(...) {...}
```

It would "de-sugar" to something like this:

```
@Post(somehowExtractThePath)
@HttpCode(201)
@ApiResponse({
  status: 201
})
async handleTheRequest(...) {...}
```

Problems:
0. This is probably not the Nestjs way to do things :D 
1. Decorators cannot modify the type annotations of a function. So users have to explicitly write something like this:  
   ``` ts
    async handleTheRequest(params: InferTheParamsPlease<typeof SomeEndpointDescription>): InferTheReponseTypePlease<typeof SomeEndpointDescription, 201>
   ````
   Luckily, we can at least strictly type the decorator so that we can catch cases where a wrong annotation is being used.
2. The Swagger integration would be pretty hard, especially the JSON Schema feature
3. Ideally, we would define "known error responses". But I think this is not that easy with Nestjs.

Again, these were just quick notes of an idea of mine - let's talk about that in a meeting.

**Comment by georg-schwarz** [comment]
Current design improved in #91. Closing for now.
