### ISSUE TITLE
Demo mode: Refreshing not possible

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#98]
Unfortunately, we deploy to a relative route (osrgroup.github.io**/msadoc**). Routing currently loses the postfix path, making refreshing or sending the link around impossible.

**Comment by MBuchalik** [comment]
Basically, we have two issues here:
1. The router seems to ignore that we are serving the application from the subfolder `/msadoc/`
2. Even if you open the correct URL like `https://osrgroup.github.io/msadoc/login`, you will get a 404. This is because GH Pages does not know how to resolve the URL, i.e. it does not know that the part after `msadoc/` is actually handled client-side.

## Issue 1

Regarding the first issue: We need to define a `basename` on the router like this:

``` tsx
<BrowserRouter basename="/msadoc">
//...
</BrowserRouter>
```

Ideally, we would define this using an env variable.

## Issue 2

On a regular webserver, we would probably define a proper `.htaccess` rewrite or the like. But I don't think this is possible on GH Pages. 

On https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing they mention 2 options:
- Use `<HashRouter>` instead of `<BrowserRouter>`. This will make the URLs look different (they will now include a "#" like `https://osrgroup.github.io/msadoc/#/login`).
- By default, GH Pages will return a 404 page when you refresh. It seems like you can override the default 404 page. So we could either use a very simple approach where we just define a script that redirects the users to the root page. Or we use a complex setup like this: https://github.com/rafgraph/spa-github-pages

**Comment by MBuchalik** [comment]
As discussed: I will do Issue 1, @georg-schwarz will do issue 2

**Comment by georg-schwarz** [comment]
@MBuchalik I pushed the fix of issue 2 to branch [98-gh-pages-bug-part2](https://github.com/osrgroup/msadoc/tree/98-gh-pages-bug-part2).

Not tested, but when merging it to your branch you can do test deployments and see if it fixes the bug.

**Comment by georg-schwarz** [comment]
Closed by #111
